import { SocialLinkIcons } from "@/types/common";
import { SubscriptionPlanType } from "@/types/sectionsTypes/pricing";
import { v4 } from "uuid";

export function useSections() {
  const sections = [
    {
      id: v4(),
      sectionName: "Header",
      content: {
        Logo: {
          type: "text",
          text: "logo",
        },
        logo: {
          link: "",
          openNewTab: false,
        },
        links: [
          {
            text: "link 2",
            link: "",
            id: v4(),
            openNewTab: false,
            subLinks: [],
          },
          {
            text: "link 3",
            link: "",
            id: v4(),
            openNewTab: false,
            subLinks: [],
          },
          {
            text: "link 4",
            link: "",
            id: v4(),
            openNewTab: false,
            subLinks: [],
          },
        ],
        buttons: [
          {
            text: "button 1",
            link: "",
            id: v4(),
          },
          {
            text: "button 2",
            link: "",
            id: v4(),
          },
        ],
        announcement: {
          position: "above", // above, below
          text: "",
          link: "",
        },
      },
      style: {
        designName: "design1",
        designSettings: {
          logoColor: "none",
          mobileMenuIcon: "icon-1", // icon-1, icon-2, icon-3
          width: "fill", // fill , fit
          sticky: false,
          float: false,
          shadow: false,
          glass: false,
          scrollIndicator: false,
          autoHide: false,
        },
      },
    },
    {
      id: v4(),
      sectionName: "Banner",
      content: {
        label: "",
        title: "developer",
        subtitle:
          "Eslam** helps you build the best products for your customers. With our expertise and experience, we can help you take your ideas from concept to reality",
        mediaType: "image",
        imageSetting: { imageUrl: "", altText: "", id: "" },
        videoSetting: { videoUrl: "" },
        actionType: "buttons",
        form: {
          fields: [
            {
              id: v4(),
              type: "text",
              label: "First name",
              value: "First name",
              placeholder: "First name",
              required: false,
              active: true,
            },
            {
              id: v4(),
              type: "text",
              label: "Last name",
              value: "Last name",
              placeholder: "Last name",
              required: false,
              active: true,
            },
            {
              id: v4(),
              type: "email",
              label: "Email",
              value: "Email",
              placeholder: "Email",
              required: true,
              active: true,
            },
            {
              id: v4(),
              type: "tel",
              label: "Phone",
              value: "Phone",
              placeholder: "Phone",
              required: false,
              active: false,
            },
            {
              id: v4(),
              type: "textarea",
              label: "Message",
              value: "Message",
              placeholder: "Message",
              required: false,
              active: false,
            },
          ],
          countryCode: {
            code: "US",
            name: "United States",
            dialCode: "+1",
            flag: "🇺🇸",
          },
          button: { text: "button 1", link: "", id: v4() },
          successMessage: "Thank you! Your submission has been received",
        },
        buttons: [
          {
            text: "button 1",
            link: "",
            id: v4(),
          },
          {
            text: "button 2",
            link: "",
            id: v4(),
          },
        ],
      },
      style: {
        designName: "design1",
        designSettings: {
          titleSize: "xl",
          align: "center",
          subtitleWidth: "50%",
          height: {
            desktop: 460,
            mobile: 350,
          },
          video: true,
          leftTitlePosition: true,
          leftTitleWidth: "50%",
          showButtons: true,
          showForm: false,
          showVideo: false,
          sectionBackground: {
            color: "none",
            media: "",
            height: "fit",
            width: "100%",
            spacing: "xl",
          },
          imageSetting: {
            objectFit: "cover",
            backgroundColor: "primary",
            showImage: true,
          },
        },
      },
    },
    {
      id: v4(),
      sectionName: "Cards",
      content: {
        label: "",
        title: "Heading",
        subtitle: "",
        cards: [
          {
            id: v4(),
            title: "Card 1",
            text: "card 1 text",
            image: "",
            imgId: "",
            button: "",
            buttonColor: "gray",
            link: "",
          },
          {
            id: v4(),
            title: "Card 2",
            text: "card 2 text",
            image: "",
            imgId: "",
            button: "",
            buttonColor: "gray",
            link: "",
          },
          {
            id: v4(),
            title: "Card 3",
            text: "card 3 text",
            image: "",
            imgId: "",
            button: "",
            buttonColor: "gray",
            link: "",
          },
        ],
      },
      style: {
        designName: "design1",
        designSettings: {
          layout: "top",
          layoutV2: "bottom",
          grid: {
            desktop: 3,
            mobile: 1,
          },
          height: {
            desktop: 300,
            mobile: 300,
          },
          titleSize: "m",
          align: "start",
          image: true,
          cardBackground: true,
          cardBorder: false,
          leftTitlePosition: false,
          displayType: "grid",
          cardSlider: {
            desktopWidth: 300,
            mobileWidth: 300,
            autoScroll: false,
            scrollSpeed: 2,
          },
          button: true,
          sectionBackground: {
            color: "none",
            media: "",
            height: "fit",
            spacing: "l",
          },
        },
      },
    },
    {
      id: v4(),
      sectionName: "List",
      content: {
        label: "",
        title: "Heading",
        subtitle: "",
        type: "icon",
        list: [
          {
            id: v4(),
            title: "List 1",
            text: "",
            icon: "",
            link: "",
          },
          {
            id: v4(),
            title: "List 2",
            text: "",
            icon: "",
            link: "",
          },
          {
            id: v4(),
            title: "List 3",
            text: "",
            icon: "",
            link: "",
          },
          {
            id: v4(),
            title: "List 4",
            text: "",
            icon: "",
            link: "",
          },
          {
            id: v4(),
            title: "List 5",
            text: "",
            icon: "",
            link: "",
          },
          {
            id: v4(),
            title: "List 6",
            text: "",
            icon: "",
            link: "",
          },
        ],
      },
      style: {
        designName: "design1",
        designSettings: {
          layout: "row",
          grid: {
            desktop: 3,
            mobile: 1,
          },
          height: 50,
          shape: "square",
          iconColor: "none",
          textSize: "m",
          align: "start",
          icon: true,
          background: true,
          border: false,
          leftTitlePosition: false,
          displayType: "grid",
          carouselSettings: {
            desktopWidth: 200,
            mobileWidth: 200,
            autoScroll: false,
            scrollSpeed: 2,
          },
          sectionBackground: {
            color: "none",
            media: "",
            height: "fit",
            spacing: "l",
          },
        },
      },
    },
    {
      id: v4(),
      sectionName: "Accordion",
      content: {
        label: "",
        title: "Heading",
        subtitle: "",
        accordions: [
          {
            id: v4(),
            title: "Accordion 1",
            text: "Add text here",
          },
          {
            id: v4(),
            title: "Accordion 2",
            text: "Add text here",
          },
          {
            id: v4(),
            title: "Accordion 3",
            text: "Add text here",
          },
        ],
      },
      style: {
        designName: "design1",
        designSettings: {
          icon: "arrow",
          align: "start",
          background: true,
          border: false,
          leftTitlePosition: false,
          sectionBackground: {
            color: "none",
            media: "",
            height: "fit",
            spacing: "l",
          },
        },
      },
    },
    {
      id: v4(),
      sectionName: "Testimonials",
      content: {
        label: "",
        title: "Testimonials",
        subtitle: "",
        iconType: "star",
        testimonials: [
          {
            id: v4(),
            review:
              "Add a customer review that describes their experience with your product/service",
            name: "John Doe",
            bio: "@johnDoe",
            rating: 4,
            avatar: "",
            avatarId: "",
            link: "",
          },
          {
            id: v4(),
            review:
              "Add a customer review that describes their experience with your product/service",
            name: "John Doe",
            bio: "@johnDoe",
            rating: 4,
            avatar: "",
            avatarId: "",
            link: "",
          },
          {
            id: v4(),
            review:
              "Add a customer review that describes their experience with your product/service",
            name: "John Doe",
            bio: "@johnDoe",
            rating: 4,
            avatar: "",
            avatarId: "",
            link: "",
          },
        ],
      },
      style: {
        designName: "design1",
        designSettings: {
          textSize: "m",
          displayType: "grid",
          grid: {
            desktop: 3,
            mobile: 1,
          },
          shape: "square",
          align: "start",
          background: true,
          border: false,
          avatar: true,
          rating: true,
          leftTitlePosition: false,
          carouselSettings: {
            desktopWidth: 350,
            mobileWidth: 300,
            autoScroll: false,
            scrollSpeed: 2,
          },
          sectionBackground: {
            color: "none",
            media: "",
            height: "fit",
            spacing: "l",
          },
        },
      },
    },
    {
      id: v4(),
      sectionName: "Gallery",
      content: {
        label: "",
        title: "Heading",
        subtitle: "",
        photos: [
          {
            id: v4(),
            imgId: "",
            url: "",
          },
          {
            id: v4(),
            imgId: "",
            url: "",
          },
          {
            id: v4(),
            imgId: "",
            url: "",
          },
          {
            id: v4(),
            imgId: "",
            url: "",
          },
        ],
      },
      style: {
        designName: "design1",
        designSettings: {
          grid: {
            desktop: 4,
            mobile: 1,
          },
          height: {
            desktop: 250,
            mobile: 100,
          },

          leftTitlePosition: false,
          displayType: "grid",
          carouselSettings: {
            desktopWidth: 300,
            mobileWidth: 300,
            autoScroll: false,
            scrollSpeed: 2,
          },
          sectionBackground: {
            color: "none",
            media: "",
            height: "fit",
            spacing: "l",
          },
        },
      },
    },
    {
      id: v4(),
      sectionName: "Logos",
      content: {
        label: "",
        title: "Heading",
        subtitle: "",
        logos: [
          {
            id: v4(),
            lightImgId: "",
            darkImgId: "",
            urlLight: "",
            urlDark: "",
            size: {
              desktop: 1,
              mobile: 1,
            },
            link: "",
          },
          {
            id: v4(),
            lightImgId: "",
            darkImgId: "",
            urlLight: "",
            urlDark: "",
            size: {
              desktop: 1,
              mobile: 1,
            },
            link: "",
          },
          {
            id: v4(),
            lightImgId: "",
            darkImgId: "",
            urlLight: "",
            urlDark: "",
            size: {
              desktop: 1,
              mobile: 1,
            },
            link: "",
          },
          {
            id: v4(),
            lightImgId: "",
            darkImgId: "",
            urlLight: "",
            urlDark: "",
            size: {
              desktop: 1,
              mobile: 1,
            },
            link: "",
          },
        ],
      },
      style: {
        designName: "design1",
        designSettings: {
          grid: {
            desktop: 4,
            mobile: 3,
          },
          height: {
            desktop: 50,
            mobile: 100,
          },
          align: "start",
          background: true,
          border: false,
          leftTitlePosition: false,
          displayType: "grid",
          carouselSettings: {
            desktopWidth: 300,
            mobileWidth: 300,
            autoScroll: false,
            scrollSpeed: 2,
          },
          sectionBackground: {
            color: "none",
            media: "",
            height: "fit",
            spacing: "l",
          },
        },
      },
    },
    {
      id: v4(),
      sectionName: "Fluid",
      content: {
        gridLayout: {
          lg: [
            {
              w: 6,
              h: 1,
              x: 5,
              y: 6,
              i: "1",
              moved: false,
              static: false,
            },
            {
              w: 11,
              h: 5,
              x: 3,
              y: 1,
              i: "2",
              moved: false,
              static: false,
            },
            {
              w: 12,
              h: 5,
              x: 16,
              y: 1,
              i: "3",
              moved: false,
              static: false,
            },
            {
              w: 6,
              h: 1,
              x: 19,
              y: 6,
              i: "4",
              moved: false,
              static: false,
            },
            {
              w: 12,
              h: 5,
              x: 30,
              y: 1,
              i: "5",
              moved: false,
              static: false,
            },
            {
              w: 7,
              h: 1,
              x: 33,
              y: 6,
              i: "6",
              moved: false,
              static: false,
            },
          ],
          sm: [
            {
              w: 5,
              h: 1,
              x: 3,
              y: 6,
              i: "1",
              moved: false,
              static: false,
            },
            {
              w: 7,
              h: 5,
              x: 2,
              y: 1,
              i: "2",
              moved: false,
              static: false,
            },
            {
              w: 7,
              h: 5,
              x: 11,
              y: 1,
              i: "3",
              moved: false,
              static: false,
            },
            {
              w: 5,
              h: 1,
              x: 12,
              y: 6,
              i: "4",
              moved: false,
              static: false,
            },
            {
              w: 7,
              h: 4,
              x: 6,
              y: 8,
              i: "5",
              moved: false,
              static: false,
            },
            {
              w: 5,
              h: 1,
              x: 7,
              y: 12,
              i: "6",
              moved: false,
              static: false,
            },
          ],
          xs: [
            {
              w: 5,
              h: 1,
              x: 5,
              y: 5,
              i: "1",
              moved: false,
              static: false,
            },
            {
              w: 11,
              h: 4,
              x: 2,
              y: 1,
              i: "2",
              moved: false,
              static: false,
            },
            {
              w: 11,
              h: 4,
              x: 2,
              y: 7,
              i: "3",
              moved: false,
              static: false,
            },
            {
              w: 5,
              h: 1,
              x: 5,
              y: 11,
              i: "4",
              moved: false,
              static: false,
            },
            {
              w: 11,
              h: 4,
              x: 2,
              y: 13,
              i: "5",
              moved: false,
              static: false,
            },
            {
              w: 5,
              h: 1,
              x: 5,
              y: 17,
              i: "6",
              moved: false,
              static: false,
            },
          ],
        },
        gridCards: [
          {
            i: "1",
            content: "Click Me",
            w: 5,
            h: 1,
            type: "button",
            settings: {
              text: "Click Me",
              variant: "default",
              size: "sm",
              buttonDisplay: "Text only",
              alignment: "center",
              buttonIcon: "CaretRight",
              textIconGap: 8,
              iconPosition: "right",
            },
          },
          {
            i: "2",
            content: "Spell Caster",
            w: 11,
            h: 6,
            type: "image",
            settings: {
              src: "",
              imageId: "",
            },
          },
          {
            i: "3",
            content: "Spell Caster",
            w: 11,
            h: 6,
            type: "image",
            settings: {
              src: "",
              imageId: "",
            },
          },
          {
            i: "4",
            content: "Click Me",
            w: 5,
            h: 1,
            type: "button",
            settings: {
              text: "Click Me",
              variant: "default",
              size: "sm",
              buttonDisplay: "Text only",
              alignment: "center",
              buttonIcon: "CaretRight",
              textIconGap: 8,
              iconPosition: "right",
            },
          },
          {
            i: "5",
            content: "Spell Caster",
            w: 11,
            h: 6,
            type: "image",
            settings: {
              imageId: "",
              src: "",
            },
          },
          {
            i: "6",
            content: "Click Me",
            w: 5,
            h: 1,
            type: "button",
            settings: {
              text: "Click Me",
              variant: "default",
              size: "sm",
              buttonDisplay: "Text only",
              alignment: "center",
              buttonIcon: "CaretRight",
              textIconGap: 8,
              iconPosition: "right",
            },
          },
        ],
      },
      style: {
        designName: "design1",
        minHeights: {
          lg: 395,
          md: 700,
          xs: 930,
        },
        gridSettings: {
          cols: { lg: 45, sm: 20, xs: 15 },
          rowHeight: 40,
          padding: [10, 10],
        },
        designSettings: {},
      },
    },
    {
      id: v4(),
      sectionName: "Footer",
      content: {
        siteLogo: true,
        text: "Add a short descriptive text",
        links: [
          {
            text: "Group",
            id: v4(),
            subLinks: [
              {
                text: "sub link 1",
                link: "",
                id: v4(),
              },
              {
                text: "sub link 2",
                link: "",
                id: v4(),
              },
            ],
          },
          {
            text: "Group 2",
            id: v4(),
            subLinks: [
              {
                text: "sub link 1",
                link: "",
                id: v4(),
              },
              {
                text: "sub link 2",
                link: "",
                id: v4(),
              },
            ],
          },
          {
            text: "Group 3",
            id: v4(),
            subLinks: [
              {
                text: "sub link 1",
                link: "",
                id: v4(),
              },
              {
                text: "sub link 2",
                link: "",
                id: v4(),
              },
            ],
          },
        ],
        buttons: [
          {
            text: "button 1",
            link: "",
            id: v4(),
          },
          {
            text: "button 2",
            link: "",
            id: v4(),
          },
        ],
        social: [
          { id: v4(), icon: SocialLinkIcons.LinkedIn, link: "" },
          { id: v4(), icon: SocialLinkIcons.Twitter, link: "" },
          { id: v4(), icon: SocialLinkIcons.Instagram, link: "" },
          { id: v4(), icon: SocialLinkIcons.WhatsApp, link: "" },
        ],
        copyRight: {
          leftArea: "All rights reserved.",
          rightArea: "",
        },
      },
      style: {
        designName: "design1",
      },
    },
    {
      id: v4(),
      sectionName: "Pricing",
      content: {
        label: "",
        title: "Heading",
        subtitle: "",
        currency: { code: "USD", name: "US Dollar", symbol: "$" },
        planType: SubscriptionPlanType.ONETIME,
        subscriptionPlans: [
          {
            billingCycle: "Monthly",
            cycleDuration: "per month",
            default: true,
          },
          {
            billingCycle: "Yearly",
            cycleDuration: "per month paid yearly",
            default: false,
          },
          {
            billingCycle: "",
            cycleDuration: "",
            default: false,
          },
        ],
        subscriptions: [
          {
            id: v4(),
            title: "Free",
            text: "",
            benefits: [
              {
                id: v4(),
                title: "Benefit 1",
              },
            ],
            oneTimePlan: {
              id: v4(),
              originalPrice: 0,
              salePrice: 0,
              isSale: false,
              offer: "",
              button: {
                text: "Get Started",
                link: "",
                openNewTab: false,
              },
            },
            price: [
              {
                originalPrice: "0",
                salePrice: "0",
                isSale: false,
                offer: "",
                button: {
                  text: "Get Started",
                  link: "",
                  openNewTab: false,
                },
              },
              {
                originalPrice: "0",
                salePrice: "0",
                isSale: false,
                offer: "",
                button: {
                  text: "Get Started",
                  link: "",
                  openNewTab: false,
                },
              },
              {
                originalPrice: "0",
                salePrice: "0",
                isSale: false,
                offer: "",
                button: {
                  text: "Get Started",
                  link: "",
                  openNewTab: false,
                },
              },
            ],
            featured: {
              isActive: false,
              text: "Best Deal",
            },
          },
          {
            id: v4(),
            title: "Start",
            text: "",
            benefits: [
              {
                id: v4(),
                title: "Benefit 1",
              },
              {
                id: v4(),
                title: "Benefit 2",
              },
              {
                id: v4(),
                title: "Benefit 3",
              },
            ],
            oneTimePlan: {
              id: v4(),
              originalPrice: "20",
              salePrice: "15",
              isSale: false,
              offer: "",
              button: {
                text: "Get Started",
                link: "",
                openNewTab: false,
              },
            },
            price: [
              {
                originalPrice: "15",
                salePrice: "10",
                isSale: false,
                offer: "",
                button: {
                  text: "Get Started",
                  link: "",
                  openNewTab: false,
                },
              },
              {
                originalPrice: "30",
                salePrice: "25",
                isSale: false,
                offer: "",
                button: {
                  text: "Get Started",
                  link: "",
                  openNewTab: false,
                },
              },
              {
                originalPrice: "0",
                salePrice: "0",
                isSale: false,
                offer: "",
                button: {
                  text: "Get Started",
                  link: "",
                  openNewTab: false,
                },
              },
            ],
            featured: {
              isActive: false,
              text: "Best Deal",
            },
          },
          {
            id: v4(),
            title: "Pro",
            text: "",
            benefits: [
              {
                id: v4(),
                title: "Benefit 1",
              },
              {
                id: v4(),
                title: "Benefit 2",
              },
              {
                id: v4(),
                title: "Benefit 3",
              },
            ],
            oneTimePlan: {
              id: v4(),
              originalPrice: "30",
              salePrice: "25",
              isSale: false,
              offer: "",
              button: {
                text: "Get Started",
                link: "",
                openNewTab: false,
              },
            },
            price: [
              {
                originalPrice: "30",
                salePrice: "15",
                isSale: false,
                offer: "",
                button: {
                  text: "Get Started",
                  link: "",
                  openNewTab: false,
                },
              },
              {
                originalPrice: "25",
                salePrice: "15",
                isSale: false,
                offer: "",
                button: {
                  text: "Get Started",
                  link: "",
                  openNewTab: false,
                },
              },
              {
                originalPrice: "0",
                salePrice: "0",
                isSale: false,
                offer: "",
                button: {
                  text: "Get Started",
                  link: "",
                  openNewTab: false,
                },
              },
            ],
            featured: {
              isActive: false,
              text: "Best Deal",
            },
          },
          {
            id: v4(),
            title: "Plus",
            text: "",
            benefits: [
              {
                id: v4(),
                title: "Benefit 1",
              },
              {
                id: v4(),
                title: "Benefit 2",
              },
              {
                id: v4(),
                title: "Benefit 3",
              },
            ],
            oneTimePlan: {
              id: v4(),
              originalPrice: "60",
              salePrice: "50",
              isSale: false,
              offer: "",
              button: {
                text: "Get Started",
                link: "",
                openNewTab: false,
              },
            },
            price: [
              {
                originalPrice: "60",
                salePrice: "50",
                isSale: false,
                offer: "",
                button: {
                  text: "Get Started",
                  link: "",
                  openNewTab: false,
                },
              },
              {
                originalPrice: "50",
                salePrice: "40",
                isSale: false,
                offer: "",
                button: {
                  text: "Get Started",
                  link: "",
                  openNewTab: false,
                },
              },
              {
                originalPrice: "700",
                salePrice: "0",
                isSale: false,
                offer: "",
                button: {
                  text: "Get Started",
                  link: "",
                  openNewTab: false,
                },
              },
            ],
            featured: {
              isActive: false,
              text: "Best Deal",
            },
          },
        ],
      },
      style: {
        designName: "design1",
        designSettings: {
          text: "m",
          background: true,
          border: false,
          sectionBackground: {
            color: "none",
            media: "",
            height: "fit",
            spacing: "l",
          },
        },
      },
    },
  ];

  return { sections };
}
