import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@/reduxStore/providers";
import Head from "./editor/head";
import { ThemeProvider } from "@/lib/theme-provider";
import { Suspense } from "react";
import Toaster from "@/components/shared/toaster/";
import TopBar from "@/components/shared/topBar";
import { createClient } from "@/utlis/supabase/server";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  return (
    <Providers>
      <html lang="en" style={{ colorScheme: "dark" }} className="dark">
        <Head />
        <body>
          <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
            <TopBar user={user} />
            <main>{children}</main>
          </ThemeProvider>
          <Suspense>
            <Toaster />
          </Suspense>
        </body>
      </html>
    </Providers>
  );
}
