import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@/reduxStore/providers";
import Editor from "./editor";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <Editor>{children}</Editor>
      </Providers>
    </html>
  );
}
