import { v4 } from "uuid";

export const about = [
  {
    sections: [
      {
        id: v4(),
        sectionName: "Banner",
        content: {
          label: "",
          title: "developer",
          subtitle:
            "Eslam** helps you build the best products for your customers. With our expertise and experience, we can help you take your ideas from concept to reality",
          mediaType: "image",
          imageSetting: { imageUrl: "", altText: "" },
          videoSetting: { videoUrl: "" },
          actionType: "buttons",
          form: {
            fields: [
              {
                id: v4(),
                type: "text",
                label: "First name",
                value: "First name",
                placeholder: "First name",
                required: false,
                active: true,
              },
              {
                id: v4(),
                type: "text",
                label: "Last name",
                value: "Last name",
                placeholder: "Last name",
                required: false,
                active: true,
              },
              {
                id: v4(),
                type: "email",
                label: "Email",
                value: "Email",
                placeholder: "Email",
                required: true,
                active: true,
              },
              {
                id: v4(),
                type: "tel",
                label: "Phone",
                value: "Phone",
                placeholder: "Phone",
                required: false,
                active: false,
              },
              {
                id: v4(),
                type: "textarea",
                label: "Message",
                value: "Message",
                placeholder: "Message",
                required: false,
                active: false,
              },
            ],
            countryCode: {
              code: "US",
              name: "United States",
              dialCode: "+1",
              flag: "🇺🇸",
            },
            button: { text: "button 1", link: "", id: v4() },
            successMessage: "Thank you! Your submission has been received",
          },
          buttons: [
            {
              text: "button 1",
              link: "",
              id: v4(),
            },
            {
              text: "button 2",
              link: "",
              id: v4(),
            },
          ],
        },
        style: {
          designName: "design1",
          designSettings: {
            titleSize: "xl",
            align: "center",
            subtitleWidth: "50%",
            height: {
              desktop: 390,
              mobile: 350,
            },
            video: true,
            leftTitlePosition: true,
            leftTitleWidth: "50%",
            showButtons: true,
            showForm: false,
            sectionBackground: {
              color: "gray",
              media: "",
              height: "fit",
              width: "100%",
              spacing: "xl",
            },
            imageSetting: {
              objectFit: "cover",
              backgroundColor: "primary",
              showImage: true,
            },
          },
        },
      },
      {
        id: v4(),
        sectionName: "Cards",
        content: {
          label: "",
          title: "Heading",
          subtitle: "",
          cards: [
            {
              id: v4(),
              title: "Card 1",
              text: "card 1 text",
              image: "",
              button: "",
              buttonColor: "gray",
              link: "",
            },
            {
              id: v4(),
              title: "Card 2",
              text: "card 2 text",
              image: "",
              button: "",
              buttonColor: "gray",
              link: "",
            },
            {
              id: v4(),
              title: "Card 3",
              text: "card 3 text",
              image: "",
              button: "",
              buttonColor: "gray",
              link: "",
            },
          ],
        },
        style: {
          designName: "design1",
          designSettings: {
            layout: "top",
            layoutV2: "bottom",
            grid: {
              desktop: 3,
              mobile: 1,
            },
            height: {
              desktop: 300,
              mobile: 300,
            },
            titleSize: "m",
            align: "start",
            image: true,
            cardBackground: true,
            cardBorder: false,
            leftTitlePosition: false,
            displayType: "grid",
            cardSlider: {
              desktopWidth: 300,
              mobileWidth: 300,
              autoScroll: false,
              scrollSpeed: 2,
            },
            button: true,
            sectionBackground: {
              color: "none",
              media: "",
              height: "fit",
              spacing: "l",
            },
          },
        },
      },
      {
        id: v4(),
        sectionName: "Testimonials",
        content: {
          label: "",
          title: "Testimonials",
          subtitle: "",
          iconType: "star",
          testimonials: [
            {
              id: v4(),
              review:
                "Add a customer review that describes their experience with your product/service",
              name: "John Doe",
              bio: "@johnDoe",
              rating: 4,
              avatar: "",
              link: "",
            },
            {
              id: v4(),
              review:
                "Add a customer review that describes their experience with your product/service",
              name: "John Doe",
              bio: "@johnDoe",
              rating: 4,
              avatar: "",
              link: "",
            },
            {
              id: v4(),
              review:
                "Add a customer review that describes their experience with your product/service",
              name: "John Doe",
              bio: "@johnDoe",
              rating: 4,
              avatar: "",
              link: "",
            },
          ],
        },
        style: {
          designName: "design1",
          designSettings: {
            textSize: "m",
            displayType: "grid",
            grid: {
              desktop: 3,
              mobile: 1,
            },
            shape: "square",
            align: "start",
            background: true,
            border: false,
            avatar: true,
            rating: true,
            leftTitlePosition: false,
            carouselSettings: {
              desktopWidth: 350,
              mobileWidth: 300,
              autoScroll: false,
              scrollSpeed: 2,
            },
            sectionBackground: {
              color: "none",
              media: "",
              height: "fit",
              spacing: "l",
            },
          },
        },
      },
    ],
  },
  {
    sections: [
      {
        id: v4(),
        sectionName: "Banner",
        content: {
          label: "",
          title: "developer",
          subtitle:
            "Eslam** helps you build the best products for your customers. With our expertise and experience, we can help you take your ideas from concept to reality",
          mediaType: "image",
          imageSetting: { imageUrl: "", altText: "" },
          videoSetting: { videoUrl: "" },
          actionType: "buttons",
          form: {
            fields: [
              {
                id: v4(),
                type: "text",
                label: "First name",
                value: "First name",
                placeholder: "First name",
                required: false,
                active: true,
              },
              {
                id: v4(),
                type: "text",
                label: "Last name",
                value: "Last name",
                placeholder: "Last name",
                required: false,
                active: true,
              },
              {
                id: v4(),
                type: "email",
                label: "Email",
                value: "Email",
                placeholder: "Email",
                required: true,
                active: true,
              },
              {
                id: v4(),
                type: "tel",
                label: "Phone",
                value: "Phone",
                placeholder: "Phone",
                required: false,
                active: false,
              },
              {
                id: v4(),
                type: "textarea",
                label: "Message",
                value: "Message",
                placeholder: "Message",
                required: false,
                active: false,
              },
            ],
            countryCode: {
              code: "US",
              name: "United States",
              dialCode: "+1",
              flag: "🇺🇸",
            },
            button: { text: "button 1", link: "", id: v4() },
            successMessage: "Thank you! Your submission has been received",
          },
          buttons: [
            {
              text: "button 1",
              link: "",
              id: v4(),
            },
            {
              text: "button 2",
              link: "",
              id: v4(),
            },
          ],
        },
        style: {
          designName: "design2",
          designSettings: {
            titleSize: "xl",
            align: "center",
            subtitleWidth: "50%",
            height: {
              desktop: 390,
              mobile: 350,
            },
            video: true,
            leftTitlePosition: true,
            leftTitleWidth: "50%",
            showButtons: true,
            showForm: false,
            sectionBackground: {
              color: "none",
              media: "",
              height: "fit",
              width: "100%",
              spacing: "xl",
            },
            imageSetting: {
              objectFit: "cover",
              backgroundColor: "primary",
              showImage: true,
            },
          },
        },
      },
      {
        id: v4(),
        sectionName: "Accordion",
        content: {
          label: "",
          title: "Heading",
          subtitle: "",
          accordions: [
            {
              id: v4(),
              title: "Accordion 1",
              text: "Add text here",
            },
            {
              id: v4(),
              title: "Accordion 2",
              text: "Add text here",
            },
            {
              id: v4(),
              title: "Accordion 3",
              text: "Add text here",
            },
          ],
        },
        style: {
          designName: "design1",
          designSettings: {
            icon: "arrow",
            align: "start",
            background: true,
            border: false,
            leftTitlePosition: false,
            sectionBackground: {
              color: "none",
              media: "",
              height: "fit",
              spacing: "l",
            },
          },
        },
      },
      {
        id: v4(),
        sectionName: "Cards",
        content: {
          label: "",
          title: "Heading",
          subtitle: "",
          cards: [
            {
              id: v4(),
              title: "Card 1",
              text: "card 1 text",
              image: "",
              button: "",
              buttonColor: "gray",
              link: "",
            },
            {
              id: v4(),
              title: "Card 2",
              text: "card 2 text",
              image: "",
              button: "",
              buttonColor: "gray",
              link: "",
            },
            {
              id: v4(),
              title: "Card 3",
              text: "card 3 text",
              image: "",
              button: "",
              buttonColor: "gray",
              link: "",
            },
          ],
        },
        style: {
          designName: "design1",
          designSettings: {
            layout: "top",
            layoutV2: "bottom",
            grid: {
              desktop: 3,
              mobile: 1,
            },
            height: {
              desktop: 300,
              mobile: 300,
            },
            titleSize: "m",
            align: "start",
            image: true,
            cardBackground: true,
            cardBorder: false,
            leftTitlePosition: false,
            displayType: "grid",
            cardSlider: {
              desktopWidth: 300,
              mobileWidth: 300,
              autoScroll: false,
              scrollSpeed: 2,
            },
            button: true,
            sectionBackground: {
              color: "none",
              media: "",
              height: "fit",
              spacing: "l",
            },
          },
        },
      },
    ],
  },
];
