export const about = [
  {
    sections: [
      {
        id: "3ec6f59c-9759-4500-99a9-fff693cfe1ee",
        style: {
          designName: "design1",
          designSettings: {
            align: "center",
            video: true,
            height: {
              mobile: 350,
              desktop: 400,
            },
            mobile: "flex-col-reverse",
            spacing: {
              gap: {
                mobile: 20,
                desktop: 50,
              },
              top: {
                mobile: 25,
                desktop: 50,
              },
              bottom: {
                mobile: 25,
                desktop: 50,
              },
              padding: {
                mobile: 10,
                desktop: 20,
              },
            },
            showForm: false,
            showVideo: false,
            titleSize: "xl",
            showButtons: false,
            imageSetting: {
              objectFit: "cover",
              showImage: true,
              backgroundColor: "primary",
            },
            subtitleWidth: "50%",
            leftTitleWidth: "50%",
            leftTitlePosition: false,
            sectionBackground: {
              color: "gray",
              media: "",
              width: "100%",
              height: "fit",
              spacing: "xl",
            },
          },
        },
        content: {
          form: {
            button: {
              id: "6e623d7e-3adf-4c70-ab74-b31fddab7944",
              link: "",
              text: "Sign Up",
            },
            fields: [
              {
                id: "a100ed0d-9c05-4257-ad1a-db85f5147b9e",
                type: "text",
                label: "First name",
                value: "First name",
                active: false,
                required: false,
                placeholder: "First name",
              },
              {
                id: "980f6c54-70ce-468b-8f3f-24b95c21fce7",
                type: "text",
                label: "Last name",
                value: "Last name",
                active: false,
                required: false,
                placeholder: "Last name",
              },
              {
                id: "2b000b31-d6a6-484e-acd3-a8ac88abfb6f",
                type: "email",
                label: "Email",
                value: "Email",
                active: true,
                required: true,
                placeholder: "Email",
              },
              {
                id: "533e7bd3-b527-4051-be2c-db291b6f7e0b",
                type: "tel",
                label: "Phone",
                value: "Phone",
                active: false,
                required: false,
                placeholder: "Phone",
              },
              {
                id: "149e69a8-7e24-4d63-9d74-7452af22e005",
                type: "textarea",
                label: "Message",
                value: "Message",
                active: false,
                required: false,
                placeholder: "Message",
              },
            ],
            countryCode: {
              code: "US",
              flag: "🇺🇸",
              name: "United States",
              dialCode: "+1",
            },
            successMessage: "Thank you! Your submission has been received",
          },
          label: "",
          title: "About 1",
          buttons: [
            {
              id: "3061d89e-a89c-4119-b4d4-721d1a53121a",
              link: "",
              text: "button 1",
              pageId: "",
              linkType: "internal",
              openNewTab: false,
              externalLink: "",
            },
            {
              id: "a9890b9d-7345-4516-93e4-2b8eebb3a6e0",
              link: "",
              text: "button 2",
              pageId: "",
              linkType: "internal",
              openNewTab: false,
              externalLink: "",
            },
          ],
          subtitle:
            "Introduce your brand or yourself with a compelling headline that connects with your audience and and establish a sense of trust and authenticity. Keep it short, interesting and easy to remember.",
          mediaType: "image",
          actionType: "form",
          imageSetting: {
            altText: "",
            imageUrl: "",
          },
          videoSetting: {
            videoUrl: "",
          },
        },
        sectionName: "Banner",
      },
      {
        id: "c0d26fb9-c767-47d2-a454-925a2f9df8b3",
        style: {
          designName: "design3",
          designSettings: {
            align: "start",
            video: true,
            height: {
              mobile: 300,
              desktop: 300,
            },
            mobile: "flex-col-reverse",
            spacing: {
              gap: {
                mobile: 20,
                desktop: 50,
              },
              top: {
                mobile: 25,
                desktop: 50,
              },
              bottom: {
                mobile: 25,
                desktop: 50,
              },
              padding: {
                mobile: 10,
                desktop: 20,
              },
            },
            showForm: false,
            showVideo: false,
            titleSize: "s",
            showButtons: false,
            imageSetting: {
              objectFit: "cover",
              showImage: true,
              backgroundColor: "primary",
            },
            subtitleWidth: "50%",
            leftTitleWidth: "50%",
            leftTitlePosition: false,
            sectionBackground: {
              blur: false,
              color: "none",
              media: {
                imageId: "",
                imageUrl: "",
              },
              height: "fit",
              overlay: false,
              spacing: "l",
              parallax: false,
              greyScale: false,
              textColor: "light",
              blurEffect: "s",
              overlayEffect: "s",
            },
          },
        },
        content: {
          form: {
            button: {
              id: "0c052d33-5ef1-43ab-8925-e5ade983840b",
              link: "",
              text: "button 1",
            },
            fields: [
              {
                id: "6b24d7b3-47ba-4561-8681-2cf835f9618e",
                type: "text",
                label: "First name",
                value: "First name",
                active: true,
                required: false,
                placeholder: "First name",
              },
              {
                id: "71a98bfa-24a9-4044-8309-b39c339e7619",
                type: "text",
                label: "Last name",
                value: "Last name",
                active: true,
                required: false,
                placeholder: "Last name",
              },
              {
                id: "8c20f8ea-a953-4e8a-b60d-c2dd554de2f8",
                type: "email",
                label: "Email",
                value: "Email",
                active: true,
                required: true,
                placeholder: "Email",
              },
              {
                id: "d00777d1-4682-498e-9ac0-af8631fe45ac",
                type: "tel",
                label: "Phone",
                value: "Phone",
                active: false,
                required: false,
                placeholder: "Phone",
              },
              {
                id: "b2169b88-4783-421a-8e9f-2d5e05060296",
                type: "textarea",
                label: "Message",
                value: "Message",
                active: false,
                required: false,
                placeholder: "Message",
              },
            ],
            countryCode: {
              code: "US",
              flag: "🇺🇸",
              name: "United States",
              dialCode: "+1",
            },
            successMessage: "Thank you! Your submission has been received",
          },
          label: "",
          title: "Your brand's journey",
          buttons: [
            {
              id: "30ef541e-8c51-47ed-a958-bbe66fe9e7e0",
              link: "",
              text: "button 1",
              pageId: "",
              linkType: "internal",
              openNewTab: false,
              externalLink: "",
            },
            {
              id: "8489272a-63f9-498d-9f84-041d56460cde",
              link: "",
              text: "button 2",
              pageId: "",
              linkType: "internal",
              openNewTab: false,
              externalLink: "",
            },
          ],
          subtitle:
            "Share a story about the origin of  the brand. Ensure it connects emotionally with the reader and provides an inspirational backstory that sets the stage for the brand's value and mission.",
          mediaType: "image",
          actionType: "buttons",
          imageSetting: {
            id: "",
            altText: "",
            imageUrl: "",
          },
          videoSetting: {
            videoUrl: "",
          },
        },
        sectionName: "Banner",
      },
      {
        id: "f6a4df36-3e55-45bd-8a6c-bf5431160588",
        style: {
          designName: "design1",
          designSettings: {
            grid: {
              mobile: 1,
              desktop: 3,
            },
            icon: true,
            align: "start",
            shape: "rounded",
            border: false,
            height: 75,
            layout: "row",
            layout2: "row",
            spacing: {
              gap: {
                mobile: 10,
                desktop: 20,
              },
              top: {
                mobile: 25,
                desktop: 50,
              },
              bottom: {
                mobile: 25,
                desktop: 50,
              },
              padding: {
                mobile: 10,
                desktop: 20,
              },
            },
            textSize: "m",
            iconColor: "primary",
            background: true,
            displayType: "grid",
            carouselSettings: {
              autoScroll: false,
              mobileWidth: 200,
              scrollSpeed: 2,
              desktopWidth: 200,
            },
            leftTitlePosition: false,
            sectionBackground: {
              blur: false,
              color: "gray",
              media: {
                imageId: "",
                imageUrl: "",
              },
              height: "fit",
              overlay: false,
              spacing: "l",
              parallax: false,
              greyScale: false,
              textColor: "light",
              blurEffect: "s",
              overlayEffect: "s",
            },
          },
        },
        content: {
          list: [
            {
              id: "c94db7ce-ab46-409e-b8cb-ac9344975cb1",
              icon: "",
              link: "",
              text: "Job title",
              title: "Full name",
            },
            {
              id: "88e69f5f-1326-43fc-bda4-48619fac52fa",
              icon: "",
              link: "",
              text: "Job title",
              title: "Full name",
            },
            {
              id: "48363cce-81aa-436d-b85c-20ebfccbb4e6",
              icon: "",
              link: "",
              text: "Job title",
              title: "Full name",
            },
            {
              id: "a684aecb-fac6-4054-ad6d-78a28c75b801",
              icon: "",
              link: "",
              text: "Job title",
              title: "Full name",
            },
            {
              id: "c86184c6-6603-405d-9d2c-f2c4efb4949b",
              icon: "",
              link: "",
              text: "Job title",
              title: "Full name",
            },
            {
              id: "a822460c-cc7a-43c6-bb97-a03a5596c91d",
              icon: "",
              link: "",
              text: "Job title",
              title: "Full name",
            },
          ],
          type: "icon",
          label: "",
          title: "Your team",
          subtitle: "",
        },
        sectionName: "List",
      },
      {
        id: "454d991a-ac03-4b75-9cdc-fe44774b1767",
        style: {
          designName: "design2",
          designSettings: {
            grid: {
              mobile: 1,
              desktop: 1,
            },
            align: "center",
            shape: "rounded",
            avatar: true,
            border: false,
            rating: true,
            spacing: {
              gap: {
                mobile: 10,
                desktop: 20,
              },
              top: {
                mobile: 25,
                desktop: 50,
              },
              bottom: {
                mobile: 25,
                desktop: 50,
              },
              padding: {
                mobile: 10,
                desktop: 20,
              },
            },
            textSize: "l",
            background: true,
            displayType: "grid",
            carouselSettings: {
              autoScroll: false,
              mobileWidth: 300,
              scrollSpeed: 2,
              desktopWidth: 350,
            },
            leftTitlePosition: false,
            sectionBackground: {
              color: "none",
              media: "",
              height: "fit",
              spacing: "l",
            },
          },
        },
        content: {
          label: "",
          title: "",
          iconType: "star",
          subtitle: "",
          testimonials: [
            {
              id: "fc103795-075c-4f83-a25b-8a8481cf003c",
              bio: "@johndoe",
              link: "",
              name: "John Doe",
              avatar: "",
              rating: 4,
              review:
                '"Add a customer testimonial that describes their experience, \nhighlights the benefits, or answers the doubts about your product/service."',
            },
          ],
        },
        sectionName: "Testimonials",
      },
      {
        id: "34bf6e4c-cdea-4487-bcfb-e5af570e7866",
        style: {
          designName: "design2",
          designSettings: {
            grid: {
              mobile: 1,
              desktop: 3,
            },
            icon: true,
            align: "start",
            shape: "square",
            border: false,
            height: 40,
            layout: "row",
            layout2: "row",
            spacing: {
              gap: {
                mobile: 10,
                desktop: 20,
              },
              top: {
                mobile: 25,
                desktop: 50,
              },
              bottom: {
                mobile: 25,
                desktop: 50,
              },
              padding: {
                mobile: 10,
                desktop: 20,
              },
            },
            textSize: "m",
            iconColor: "primary",
            background: true,
            displayType: "grid",
            carouselSettings: {
              autoScroll: false,
              mobileWidth: 200,
              scrollSpeed: 2,
              desktopWidth: 200,
            },
            leftTitlePosition: false,
            sectionBackground: {
              blur: false,
              color: "gray",
              media: {
                imageId: "",
                imageUrl: "",
              },
              height: "fit",
              overlay: false,
              spacing: "l",
              parallax: false,
              greyScale: false,
              textColor: "light",
              blurEffect: "s",
              overlayEffect: "s",
            },
          },
        },
        content: {
          list: [
            {
              id: "5f8d06aa-69dd-4ce4-8973-1142b9b682f8",
              icon: "",
              link: "",
              text: "",
              title: "#1 Value",
            },
            {
              id: "9c6744c9-f06a-4651-83b9-c7871da4b37d",
              icon: "",
              link: "",
              text: "",
              title: "#2 Value",
            },
            {
              id: "1edf52a4-7519-4c77-9e74-43607dec0e1e",
              icon: "",
              link: "",
              text: "",
              title: "#3 Value",
            },
          ],
          type: "icon",
          label: "",
          title: "Your core values",
          subtitle: "",
        },
        sectionName: "List",
      },
      {
        id: "9f8cb279-fd28-442f-ac0c-bd49a56f1a08",
        style: {
          designName: "design1",
          designSettings: {
            align: "start",
            video: true,
            height: {
              mobile: 350,
              desktop: 460,
            },
            mobile: "flex-col-reverse",
            spacing: {
              gap: {
                mobile: 20,
                desktop: 50,
              },
              top: {
                mobile: 25,
                desktop: 50,
              },
              bottom: {
                mobile: 25,
                desktop: 50,
              },
              padding: {
                mobile: 10,
                desktop: 20,
              },
            },
            showForm: true,
            showVideo: false,
            titleSize: "s",
            showButtons: false,
            imageSetting: {
              objectFit: "cover",
              showImage: false,
              backgroundColor: "primary",
            },
            subtitleWidth: "50%",
            leftTitleWidth: "56%",
            leftTitlePosition: true,
            sectionBackground: {
              color: "none",
              media: "",
              width: "100%",
              height: "fit",
              spacing: "xl",
            },
          },
        },
        content: {
          form: {
            button: {
              id: "ae56c192-0855-487c-9bc2-046aecf4cb44",
              link: "",
              text: "Sign Up",
            },
            fields: [
              {
                id: "54ff7ba9-ce48-4c86-86ff-15a42c018e6e",
                type: "text",
                label: "First name",
                value: "First name",
                active: false,
                required: false,
                placeholder: "First name",
              },
              {
                id: "9a038b96-a185-4c57-80ef-65700b9ef1fc",
                type: "text",
                label: "Last name",
                value: "Last name",
                active: false,
                required: false,
                placeholder: "Last name",
              },
              {
                id: "8bfb36cf-b4ba-49d8-b22a-2faae99ba31b",
                type: "email",
                label: "Email",
                value: "Email",
                active: true,
                required: true,
                placeholder: "Email",
              },
              {
                id: "fa641a07-4314-4acd-a259-9bc9ccfa9d13",
                type: "tel",
                label: "Phone",
                value: "Phone",
                active: false,
                required: false,
                placeholder: "Phone",
              },
              {
                id: "9249762c-dc58-4409-bfdc-290b08303287",
                type: "textarea",
                label: "Message",
                value: "Message",
                active: false,
                required: false,
                placeholder: "Message",
              },
            ],
            countryCode: {
              code: "US",
              flag: "🇺🇸",
              name: "United States",
              dialCode: "+1",
            },
            successMessage: "Thank you! Your submission has been received",
          },
          label: "",
          title: "Headline that excite \nvisitors to subscribe",
          buttons: [
            {
              id: "cf41a625-4f52-4d78-a1f5-1fcb7ccbad7f",
              link: "",
              text: "",
              pageId: "",
              linkType: "internal",
              openNewTab: false,
              externalLink: "",
            },
            {
              id: "0790a9d6-5327-4925-918c-6b19ec6d05c9",
              link: "",
              text: "Get Started",
              pageId: "",
              linkType: "internal",
              openNewTab: false,
              externalLink: "",
            },
          ],
          subtitle:
            "Use strong action verbs and clear language that conveys the benefit or value of completing the action.",
          mediaType: "image",
          actionType: "form",
          imageSetting: {
            altText: "",
            imageUrl: "",
          },
          videoSetting: {
            videoUrl: "",
          },
        },
        sectionName: "Banner",
      },
    ],
  },
  {
    sections: [
      {
        id: "3ec6f59c-9759-4500-99a9-fff693cfe1ee",
        style: {
          designName: "design1",
          designSettings: {
            align: "start",
            video: true,
            height: {
              mobile: 350,
              desktop: 400,
            },
            mobile: "flex-col-reverse",
            spacing: {
              gap: {
                mobile: 20,
                desktop: 50,
              },
              top: {
                mobile: 25,
                desktop: 50,
              },
              bottom: {
                mobile: 25,
                desktop: 50,
              },
              padding: {
                mobile: 10,
                desktop: 20,
              },
            },
            showForm: false,
            showVideo: false,
            titleSize: "xl",
            showButtons: false,
            imageSetting: {
              objectFit: "cover",
              showImage: false,
              backgroundColor: "primary",
            },
            subtitleWidth: "65%",
            leftTitleWidth: "50%",
            leftTitlePosition: false,
            sectionBackground: {
              color: "primary",
              media: "",
              width: "100%",
              height: "fit",
              spacing: "xl",
            },
            background: true,
            border: false,
          },
        },
        content: {
          form: {
            button: {
              id: "6e623d7e-3adf-4c70-ab74-b31fddab7944",
              link: "",
              text: "Sign Up",
            },
            fields: [
              {
                id: "a100ed0d-9c05-4257-ad1a-db85f5147b9e",
                type: "text",
                label: "First name",
                value: "First name",
                active: false,
                required: false,
                placeholder: "First name",
              },
              {
                id: "980f6c54-70ce-468b-8f3f-24b95c21fce7",
                type: "text",
                label: "Last name",
                value: "Last name",
                active: false,
                required: false,
                placeholder: "Last name",
              },
              {
                id: "2b000b31-d6a6-484e-acd3-a8ac88abfb6f",
                type: "email",
                label: "Email",
                value: "Email",
                active: true,
                required: true,
                placeholder: "Email",
              },
              {
                id: "533e7bd3-b527-4051-be2c-db291b6f7e0b",
                type: "tel",
                label: "Phone",
                value: "Phone",
                active: false,
                required: false,
                placeholder: "Phone",
              },
              {
                id: "149e69a8-7e24-4d63-9d74-7452af22e005",
                type: "textarea",
                label: "Message",
                value: "Message",
                active: false,
                required: false,
                placeholder: "Message",
              },
            ],
            countryCode: {
              code: "US",
              flag: "🇺🇸",
              name: "United States",
              dialCode: "+1",
            },
            successMessage: "Thank you! Your submission has been received",
          },
          label: "",
          title: "About us",
          buttons: [
            {
              id: "3061d89e-a89c-4119-b4d4-721d1a53121a",
              link: "",
              text: "button 1",
              pageId: "",
              linkType: "internal",
              openNewTab: false,
              externalLink: "",
            },
            {
              id: "a9890b9d-7345-4516-93e4-2b8eebb3a6e0",
              link: "",
              text: "button 2",
              pageId: "",
              linkType: "internal",
              openNewTab: false,
              externalLink: "",
            },
          ],
          subtitle:
            "Introduce your brand or yourself with a compelling headline that connects with your audience and and establish a sense of trust and authenticity. Keep it short, interesting and easy to remember.",
          mediaType: "image",
          actionType: "form",
          imageSetting: {
            altText: "",
            imageUrl: "",
          },
          videoSetting: {
            videoUrl: "",
          },
        },
        sectionName: "Banner",
      },
      {
        id: "d307a86c-80c1-40b2-a954-f48693c23762",
        sectionName: "Gallery",
        content: {
          label: "",
          title: "Your brand's journey",
          subtitle:
            "Share a story about the origin of  the brand. Ensure it connects emotionally with the reader and provides an inspirational backstory that sets the stage for the brand's value and mission.",
          photos: [
            {
              id: "eb5496ea-cf18-472f-9514-0f78878de859",
              imgId: "",
              url: "",
            },
            {
              id: "30416cfe-9d80-4709-bba4-ffd66d92d276",
              imgId: "",
              url: "",
            },
            {
              id: "4c2521f9-8f5e-4250-b8d2-42b501cdb075",
              imgId: "",
              url: "",
            },
            {
              id: "3969f416-1e1f-4d35-8153-46e27280e3e0",
              imgId: "",
              url: "",
            },
            {
              id: "3102e223-e300-450c-98bd-f4f81e112db2",
              url: "",
              imgId: "",
            },
            {
              id: "356a2c95-5190-4ae8-bc7a-cdb00e95611e",
              url: "",
              imgId: "",
            },
            {
              id: "1d3c727e-070c-4949-9861-5b8c176cb0d0",
              url: "",
              imgId: "",
            },
            {
              id: "9b383835-9198-402b-ae2b-f44608472126",
              url: "",
              imgId: "",
            },
          ],
        },
        style: {
          designName: "design1",
          designSettings: {
            grid: {
              desktop: 4,
              mobile: 3,
            },
            height: {
              desktop: 250,
              mobile: 100,
            },
            leftTitlePosition: false,
            displayType: "grid",
            carouselSettings: {
              desktopWidth: 300,
              mobileWidth: 300,
              autoScroll: false,
              scrollSpeed: 2,
            },
            spacing: {
              top: {
                desktop: 50,
                mobile: 25,
              },
              bottom: {
                desktop: 50,
                mobile: 25,
              },
              gap: {
                desktop: 20,
                mobile: 10,
              },
              padding: {
                desktop: 20,
                mobile: 10,
              },
            },
            sectionBackground: {
              color: "none",
              media: {
                imageUrl: "",
                imageId: "",
              },
              textColor: "light",
              height: "fit",
              spacing: "l",
              overlay: false,
              blur: false,
              greyScale: false,
              parallax: false,
              overlayEffect: "s",
              blurEffect: "s",
            },
          },
        },
      },
      {
        id: "34bf6e4c-cdea-4487-bcfb-e5af570e7866",
        style: {
          designName: "design2",
          designSettings: {
            grid: {
              mobile: 1,
              desktop: 3,
            },
            icon: true,
            align: "start",
            shape: "square",
            border: false,
            height: 50,
            layout: "row",
            layout2: "row",
            spacing: {
              gap: {
                mobile: 10,
                desktop: 20,
              },
              top: {
                mobile: 25,
                desktop: 50,
              },
              bottom: {
                mobile: 25,
                desktop: 50,
              },
              padding: {
                mobile: 10,
                desktop: 20,
              },
            },
            textSize: "m",
            iconColor: "primary",
            background: true,
            displayType: "grid",
            carouselSettings: {
              autoScroll: false,
              mobileWidth: 200,
              scrollSpeed: 2,
              desktopWidth: 200,
            },
            leftTitlePosition: false,
            sectionBackground: {
              blur: false,
              color: "gray",
              media: {
                imageId: "",
                imageUrl: "",
              },
              height: "fit",
              overlay: false,
              spacing: "l",
              parallax: false,
              greyScale: false,
              textColor: "light",
              blurEffect: "s",
              overlayEffect: "s",
            },
          },
        },
        content: {
          list: [
            {
              id: "5f8d06aa-69dd-4ce4-8973-1142b9b682f8",
              icon: "",
              link: "",
              text: "",
              title: "#1 Value",
            },
            {
              id: "9c6744c9-f06a-4651-83b9-c7871da4b37d",
              icon: "",
              link: "",
              text: "",
              title: "#2 Value",
            },
            {
              id: "1edf52a4-7519-4c77-9e74-43607dec0e1e",
              icon: "",
              link: "",
              text: "",
              title: "#3 Value",
            },
          ],
          type: "icon",
          label: "",
          title: "Your core values",
          subtitle: "",
        },
        sectionName: "List",
      },
      {
        id: "f6a4df36-3e55-45bd-8a6c-bf5431160588",
        style: {
          designName: "design2",
          designSettings: {
            grid: {
              mobile: 1,
              desktop: 3,
            },
            icon: true,
            align: "start",
            shape: "square",
            border: false,
            height: 100,
            layout: "row",
            layout2: "row",
            spacing: {
              gap: {
                mobile: 10,
                desktop: 20,
              },
              top: {
                mobile: 25,
                desktop: 50,
              },
              bottom: {
                mobile: 25,
                desktop: 50,
              },
              padding: {
                mobile: 10,
                desktop: 20,
              },
            },
            textSize: "m",
            iconColor: "primary",
            background: true,
            displayType: "grid",
            carouselSettings: {
              autoScroll: false,
              mobileWidth: 200,
              scrollSpeed: 2,
              desktopWidth: 200,
            },
            leftTitlePosition: false,
            sectionBackground: {
              blur: false,
              color: "none",
              media: {
                imageId: "",
                imageUrl: "",
              },
              height: "fit",
              overlay: false,
              spacing: "l",
              parallax: false,
              greyScale: false,
              textColor: "light",
              blurEffect: "s",
              overlayEffect: "s",
            },
          },
        },
        content: {
          list: [
            {
              id: "c94db7ce-ab46-409e-b8cb-ac9344975cb1",
              icon: "",
              link: "",
              text: "Job title",
              title: "Full name",
            },
            {
              id: "88e69f5f-1326-43fc-bda4-48619fac52fa",
              icon: "",
              link: "",
              text: "Job title",
              title: "Full name",
            },
            {
              id: "48363cce-81aa-436d-b85c-20ebfccbb4e6",
              icon: "",
              link: "",
              text: "Job title",
              title: "Full name",
            },
            {
              id: "a684aecb-fac6-4054-ad6d-78a28c75b801",
              icon: "",
              link: "",
              text: "Job title",
              title: "Full name",
            },
            {
              id: "c86184c6-6603-405d-9d2c-f2c4efb4949b",
              icon: "",
              link: "",
              text: "Job title",
              title: "Full name",
            },
            {
              id: "a822460c-cc7a-43c6-bb97-a03a5596c91d",
              icon: "",
              link: "",
              text: "Job title",
              title: "Full name",
            },
          ],
          type: "icon",
          label: "",
          title: "Your team",
          subtitle: "",
        },
        sectionName: "List",
      },
      {
        id: "9f8cb279-fd28-442f-ac0c-bd49a56f1a08",
        style: {
          designName: "design1",
          designSettings: {
            align: "start",
            video: true,
            height: {
              mobile: 350,
              desktop: 460,
            },
            mobile: "flex-col-reverse",
            spacing: {
              gap: {
                mobile: 20,
                desktop: 50,
              },
              top: {
                mobile: 25,
                desktop: 50,
              },
              bottom: {
                mobile: 25,
                desktop: 50,
              },
              padding: {
                mobile: 10,
                desktop: 20,
              },
            },
            showForm: true,
            showVideo: false,
            titleSize: "s",
            showButtons: false,
            imageSetting: {
              objectFit: "cover",
              showImage: false,
              backgroundColor: "primary",
            },
            subtitleWidth: "50%",
            leftTitleWidth: "56%",
            leftTitlePosition: true,
            sectionBackground: {
              color: "gray",
              media: "",
              width: "100%",
              height: "fit",
              spacing: "xl",
            },
            background: true,
            border: false,
          },
        },
        content: {
          form: {
            button: {
              id: "ae56c192-0855-487c-9bc2-046aecf4cb44",
              link: "",
              text: "Sign Up",
            },
            fields: [
              {
                id: "54ff7ba9-ce48-4c86-86ff-15a42c018e6e",
                type: "text",
                label: "First name",
                value: "First name",
                active: false,
                required: false,
                placeholder: "First name",
              },
              {
                id: "9a038b96-a185-4c57-80ef-65700b9ef1fc",
                type: "text",
                label: "Last name",
                value: "Last name",
                active: false,
                required: false,
                placeholder: "Last name",
              },
              {
                id: "8bfb36cf-b4ba-49d8-b22a-2faae99ba31b",
                type: "email",
                label: "Email",
                value: "Email",
                active: true,
                required: true,
                placeholder: "Email",
              },
              {
                id: "fa641a07-4314-4acd-a259-9bc9ccfa9d13",
                type: "tel",
                label: "Phone",
                value: "Phone",
                active: false,
                required: false,
                placeholder: "Phone",
              },
              {
                id: "9249762c-dc58-4409-bfdc-290b08303287",
                type: "textarea",
                label: "Message",
                value: "Message",
                active: false,
                required: false,
                placeholder: "Message",
              },
            ],
            countryCode: {
              code: "US",
              flag: "🇺🇸",
              name: "United States",
              dialCode: "+1",
            },
            successMessage: "Thank you! Your submission has been received",
          },
          label: "",
          title: "Headline that excite \nvisitors to subscribe",
          buttons: [
            {
              id: "cf41a625-4f52-4d78-a1f5-1fcb7ccbad7f",
              link: "",
              text: "",
              pageId: "",
              linkType: "internal",
              openNewTab: false,
              externalLink: "",
            },
            {
              id: "0790a9d6-5327-4925-918c-6b19ec6d05c9",
              link: "",
              text: "Get Started",
              pageId: "",
              linkType: "internal",
              openNewTab: false,
              externalLink: "",
            },
          ],
          subtitle:
            "Use strong action verbs and clear language that conveys the benefit or value of completing the action.",
          mediaType: "image",
          actionType: "form",
          imageSetting: {
            altText: "",
            imageUrl: "",
          },
          videoSetting: {
            videoUrl: "",
          },
        },
        sectionName: "Banner",
      },
    ],
  },
];
