export const blank = {
  sections: [
    {
      id: "3ec6f59c-9759-4500-99a9-fff693cfe1ee",
      style: {
        designName: "design1",
        designSettings: {
          align: "center",
          video: true,
          border: false,
          height: {
            mobile: 350,
            desktop: 570,
          },
          mobile: "flex-col-reverse",
          spacing: {
            gap: {
              mobile: 20,
              desktop: 50,
            },
            top: {
              mobile: 25,
              desktop: 50,
            },
            bottom: {
              mobile: 25,
              desktop: 50,
            },
            padding: {
              mobile: 10,
              desktop: 20,
            },
          },
          showForm: false,
          showVideo: false,
          titleSize: "xl",
          background: true,
          showButtons: false,
          imageSetting: {
            objectFit: "cover",
            showImage: false,
            backgroundColor: "primary",
          },
          subtitleWidth: "50%",
          leftTitleWidth: "50%",
          leftTitlePosition: false,
          sectionBackground: {
            blur: false,
            color: "none",
            media: {
              imageId: "",
              imageUrl: "",
            },
            width: "fill",
            height: "fit",
            overlay: false,
            spacing: "xl",
            parallax: false,
            greyScale: false,
            textColor: "light",
            blurEffect: "s",
            overlayEffect: "s",
          },
        },
      },
      content: {
        form: {
          button: {
            id: "6e623d7e-3adf-4c70-ab74-b31fddab7944",
            link: "",
            text: "Submit",
          },
          fields: [
            {
              id: "a100ed0d-9c05-4257-ad1a-db85f5147b9e",
              type: "text",
              label: "First name",
              value: "First name",
              active: true,
              required: false,
              placeholder: "First name",
            },
            {
              id: "980f6c54-70ce-468b-8f3f-24b95c21fce7",
              type: "text",
              label: "Last name",
              value: "Last name",
              active: false,
              required: false,
              placeholder: "Last name",
            },
            {
              id: "2b000b31-d6a6-484e-acd3-a8ac88abfb6f",
              type: "email",
              label: "Email",
              value: "Email",
              active: true,
              required: true,
              placeholder: "Email",
            },
            {
              id: "533e7bd3-b527-4051-be2c-db291b6f7e0b",
              type: "tel",
              label: "Phone",
              value: "Phone",
              active: false,
              required: false,
              placeholder: "Phone",
            },
            {
              id: "149e69a8-7e24-4d63-9d74-7452af22e005",
              type: "textarea",
              label: "Message",
              value: "Message",
              active: false,
              required: false,
              placeholder: "Message",
            },
          ],
          countryCode: {
            code: "US",
            flag: "🇺🇸",
            name: "United States",
            dialCode: "+1",
          },
          successMessage: "Thank you! Your submission has been received",
        },
        label: "",
        title: "Main Heading",
        buttons: [
          {
            id: "3061d89e-a89c-4119-b4d4-721d1a53121a",
            link: "",
            text: "button 1",
            pageId: "",
            linkType: "internal",
            openNewTab: false,
            externalLink: "",
          },
          {
            id: "a9890b9d-7345-4516-93e4-2b8eebb3a6e0",
            link: "",
            text: "button 2",
            pageId: "",
            linkType: "internal",
            openNewTab: false,
            externalLink: "",
          },
        ],
        subtitle: "Add text here\n\n\n\n",
        mediaType: "image",
        actionType: "form",
        imageSetting: {
          altText: "",
          imageUrl: "",
        },
        videoSetting: {
          videoUrl: "",
        },
      },
      sectionName: "Banner",
    },
  ],
};
