export const contact = [
  {
    sections: [
      {
        id: "3ec6f59c-9759-4500-99a9-fff693cfe1ee",
        style: {
          designName: "design1",
          designSettings: {
            align: "center",
            video: true,
            border: false,
            height: {
              mobile: 350,
              desktop: 400,
            },
            mobile: "flex-col-reverse",
            spacing: {
              gap: {
                mobile: 20,
                desktop: 50,
              },
              top: {
                mobile: 25,
                desktop: 50,
              },
              bottom: {
                mobile: 25,
                desktop: 50,
              },
              padding: {
                mobile: 10,
                desktop: 20,
              },
            },
            showForm: true,
            showVideo: false,
            titleSize: "xl",
            background: true,
            showButtons: false,
            imageSetting: {
              objectFit: "cover",
              showImage: false,
              backgroundColor: "primary",
            },
            subtitleWidth: "50%",
            leftTitleWidth: "50%",
            leftTitlePosition: false,
            sectionBackground: {
              blur: false,
              color: "none",
              media: {
                imageId: "",
                imageUrl: "",
              },
              width: "fill",
              height: "fit",
              overlay: false,
              spacing: "xl",
              parallax: false,
              greyScale: false,
              textColor: "light",
              blurEffect: "s",
              overlayEffect: "s",
            },
          },
        },
        content: {
          form: {
            button: {
              id: "6e623d7e-3adf-4c70-ab74-b31fddab7944",
              link: "",
              text: "Submit",
            },
            fields: [
              {
                id: "a100ed0d-9c05-4257-ad1a-db85f5147b9e",
                type: "text",
                label: "First name",
                value: "First name",
                active: true,
                required: false,
                placeholder: "First name",
              },
              {
                id: "980f6c54-70ce-468b-8f3f-24b95c21fce7",
                type: "text",
                label: "Last name",
                value: "Last name",
                active: false,
                required: false,
                placeholder: "Last name",
              },
              {
                id: "2b000b31-d6a6-484e-acd3-a8ac88abfb6f",
                type: "email",
                label: "Email",
                value: "Email",
                active: true,
                required: true,
                placeholder: "Email",
              },
              {
                id: "533e7bd3-b527-4051-be2c-db291b6f7e0b",
                type: "tel",
                label: "Phone",
                value: "Phone",
                active: false,
                required: false,
                placeholder: "Phone",
              },
              {
                id: "149e69a8-7e24-4d63-9d74-7452af22e005",
                type: "textarea",
                label: "Message",
                value: "Message",
                active: false,
                required: false,
                placeholder: "Message",
              },
            ],
            countryCode: {
              code: "US",
              flag: "🇺🇸",
              name: "United States",
              dialCode: "+1",
            },
            successMessage: "Thank you! Your submission has been received",
          },
          label: "",
          title: "Contact",
          buttons: [
            {
              id: "3061d89e-a89c-4119-b4d4-721d1a53121a",
              link: "",
              text: "button 1",
              pageId: "",
              linkType: "internal",
              openNewTab: false,
              externalLink: "",
            },
            {
              id: "a9890b9d-7345-4516-93e4-2b8eebb3a6e0",
              link: "",
              text: "button 2",
              pageId: "",
              linkType: "internal",
              openNewTab: false,
              externalLink: "",
            },
          ],
          subtitle:
            "An inviting message that encourages visitors to get in touch.",
          mediaType: "image",
          actionType: "form",
          imageSetting: {
            altText: "",
            imageUrl: "",
          },
          videoSetting: {
            videoUrl: "",
          },
        },
        sectionName: "Banner",
      },
      {
        id: "cfa60d52-afca-4930-80c5-e329f6da0b44",
        sectionName: "List",
        content: {
          label: "",
          title: "",
          subtitle: "",
          type: "icon",
          list: [
            {
              id: "4ea1c4d0-eecc-482f-89ec-384b1874b3e1",
              title: "hello@team.co",
              text: "",
              icon: "Envelope",
              link: "",
              externalLink: "",
              image: "",
              imageId: "",
              linkType: "internal",
              openNewTab: false,
              pageId: "",
            },
            {
              id: "39945689-6b49-4daa-b5e7-acb1b851fca5",
              title: "+1 (234) 567 8900",
              text: "",
              icon: "DeviceMobileCamera",
              link: "",
              externalLink: "",
              image: "",
              imageId: "",
              linkType: "internal",
              openNewTab: false,
              pageId: "",
            },
            {
              id: "e618cec2-2d3a-4b28-9374-bf05cebc8ade",
              title: "123 Alphabet St, 12345, USA",
              text: "",
              icon: "MapPin",
              link: "",
              externalLink: "",
              image: "",
              imageId: "",
              linkType: "internal",
              openNewTab: false,
              pageId: "",
            },
          ],
        },
        style: {
          designName: "design2",
          designSettings: {
            layout: "row",
            layout2: "col",
            grid: {
              desktop: 3,
              mobile: 1,
            },
            height: 50,
            shape: "square",
            iconColor: "primary",
            textSize: "s",
            align: "start",
            icon: true,
            background: true,
            border: false,
            leftTitlePosition: false,
            displayType: "grid",
            carouselSettings: {
              desktopWidth: 200,
              mobileWidth: 200,
              autoScroll: false,
              scrollSpeed: 2,
            },
            spacing: {
              top: {
                desktop: 50,
                mobile: 25,
              },
              bottom: {
                desktop: 50,
                mobile: 25,
              },
              gap: {
                desktop: 20,
                mobile: 10,
              },
              padding: {
                desktop: 20,
                mobile: 10,
              },
            },
            sectionBackground: {
              color: "primary",
              media: {
                imageUrl: "",
                imageId: "",
              },
              textColor: "light",
              height: "fit",
              width: "fill",
              spacing: "l",
              overlay: false,
              blur: false,
              greyScale: false,
              parallax: false,
              overlayEffect: "s",
              blurEffect: "s",
            },
          },
        },
      },
      {
        id: "4bbb3732-8537-492e-b53f-5a123130dab1",
        style: {
          designName: "design1",
          designSettings: {
            icon: "arrow",
            align: "start",
            border: false,
            spacing: {
              gap: {
                mobile: 10,
                desktop: 20,
              },
              top: {
                mobile: 25,
                desktop: 50,
              },
              bottom: {
                mobile: 25,
                desktop: 50,
              },
              padding: {
                mobile: 10,
                desktop: 20,
              },
            },
            background: true,
            leftTitlePosition: false,
            sectionBackground: {
              blur: false,
              color: "gray",
              media: {
                imageId: "",
                imageUrl: "",
              },
              width: "fill",
              height: "fit",
              overlay: false,
              spacing: "l",
              parallax: false,
              greyScale: false,
              textColor: "light",
              blurEffect: "s",
              overlayEffect: "s",
            },
          },
        },
        content: {
          label: "",
          title: "FAQs",
          subtitle: "",
          accordions: [
            {
              id: "1de69273-4f21-4624-948a-916e6da3212b",
              text: "Add response here",
              title: "Question #1",
            },
            {
              id: "057b695e-fc2b-4446-9d74-8f7d629d3eef",
              text: "Add response here",
              title: "Question #2",
            },
            {
              id: "fbaa5bd3-cb52-4c9f-ad0d-2612f97ef65f",
              text: "Add response here",
              title: "Question #3",
            },
          ],
        },
        sectionName: "Accordion",
      },
    ],
  },
  {
    sections: [
      {
        id: "3ec6f59c-9759-4500-99a9-fff693cfe1ee",
        style: {
          designName: "design5",
          designSettings: {
            align: "center",
            video: true,
            border: false,
            height: {
              mobile: 350,
              desktop: 570,
            },
            mobile: "flex-col-reverse",
            spacing: {
              gap: {
                mobile: 20,
                desktop: 50,
              },
              top: {
                mobile: 25,
                desktop: 50,
              },
              bottom: {
                mobile: 25,
                desktop: 50,
              },
              padding: {
                mobile: 10,
                desktop: 20,
              },
            },
            showForm: true,
            showVideo: false,
            titleSize: "xl",
            background: true,
            showButtons: false,
            imageSetting: {
              objectFit: "cover",
              showImage: true,
              backgroundColor: "primary",
            },
            subtitleWidth: "50%",
            leftTitleWidth: "50%",
            leftTitlePosition: false,
            sectionBackground: {
              blur: false,
              color: "none",
              media: {
                imageId: "",
                imageUrl: "",
              },
              width: "fill",
              height: "fit",
              overlay: false,
              spacing: "xl",
              parallax: false,
              greyScale: false,
              textColor: "light",
              blurEffect: "s",
              overlayEffect: "s",
            },
          },
        },
        content: {
          form: {
            button: {
              id: "6e623d7e-3adf-4c70-ab74-b31fddab7944",
              link: "",
              text: "Submit",
            },
            fields: [
              {
                id: "a100ed0d-9c05-4257-ad1a-db85f5147b9e",
                type: "text",
                label: "First name",
                value: "First name",
                active: true,
                required: false,
                placeholder: "First name",
              },
              {
                id: "980f6c54-70ce-468b-8f3f-24b95c21fce7",
                type: "text",
                label: "Last name",
                value: "Last name",
                active: false,
                required: false,
                placeholder: "Last name",
              },
              {
                id: "2b000b31-d6a6-484e-acd3-a8ac88abfb6f",
                type: "email",
                label: "Email",
                value: "Email",
                active: true,
                required: true,
                placeholder: "Email",
              },
              {
                id: "533e7bd3-b527-4051-be2c-db291b6f7e0b",
                type: "tel",
                label: "Phone",
                value: "Phone",
                active: false,
                required: false,
                placeholder: "Phone",
              },
              {
                id: "149e69a8-7e24-4d63-9d74-7452af22e005",
                type: "textarea",
                label: "Message",
                value: "Message",
                active: false,
                required: false,
                placeholder: "Message",
              },
            ],
            countryCode: {
              code: "US",
              flag: "🇺🇸",
              name: "United States",
              dialCode: "+1",
            },
            successMessage: "Thank you! Your submission has been received",
          },
          label: "",
          title: "Contact",
          buttons: [
            {
              id: "3061d89e-a89c-4119-b4d4-721d1a53121a",
              link: "",
              text: "button 1",
              pageId: "",
              linkType: "internal",
              openNewTab: false,
              externalLink: "",
            },
            {
              id: "a9890b9d-7345-4516-93e4-2b8eebb3a6e0",
              link: "",
              text: "button 2",
              pageId: "",
              linkType: "internal",
              openNewTab: false,
              externalLink: "",
            },
          ],
          subtitle:
            "An inviting message that encourages visitors to get in touch.",
          mediaType: "image",
          actionType: "form",
          imageSetting: {
            altText: "",
            imageUrl: "",
          },
          videoSetting: {
            videoUrl: "",
          },
        },
        sectionName: "Banner",
      },
      {
        id: "cfa60d52-afca-4930-80c5-e329f6da0b44",
        style: {
          designName: "design2",
          designSettings: {
            grid: {
              mobile: 1,
              desktop: 3,
            },
            icon: true,
            align: "start",
            shape: "square",
            border: false,
            height: 50,
            layout: "row",
            layout2: "col",
            spacing: {
              gap: {
                mobile: 10,
                desktop: 20,
              },
              top: {
                mobile: 25,
                desktop: 50,
              },
              bottom: {
                mobile: 25,
                desktop: 50,
              },
              padding: {
                mobile: 10,
                desktop: 20,
              },
            },
            textSize: "s",
            iconColor: "primary",
            background: true,
            displayType: "grid",
            carouselSettings: {
              autoScroll: false,
              mobileWidth: 200,
              scrollSpeed: 2,
              desktopWidth: 200,
            },
            leftTitlePosition: false,
            sectionBackground: {
              blur: false,
              color: "gray",
              media: {
                imageId: "",
                imageUrl: "",
              },
              width: "fill",
              height: "fit",
              overlay: false,
              spacing: "l",
              parallax: false,
              greyScale: false,
              textColor: "light",
              blurEffect: "s",
              overlayEffect: "s",
            },
          },
        },
        content: {
          list: [
            {
              id: "4ea1c4d0-eecc-482f-89ec-384b1874b3e1",
              icon: "Envelope",
              link: "",
              externalLink: "",
              image: "",
              imageId: "",
              linkType: "internal",
              openNewTab: false,
              pageId: "",
              text: "",
              title: "hello@team.co",
            },
            {
              id: "39945689-6b49-4daa-b5e7-acb1b851fca5",
              icon: "DeviceMobileCamera",
              link: "",
              externalLink: "",
              image: "",
              imageId: "",
              linkType: "internal",
              openNewTab: false,
              pageId: "",
              text: "",
              title: "+1 (234) 567 8900",
            },
            {
              id: "e618cec2-2d3a-4b28-9374-bf05cebc8ade",
              icon: "MapPin",
              link: "",
              externalLink: "",
              image: "",
              imageId: "",
              linkType: "internal",
              openNewTab: false,
              pageId: "",
              text: "",
              title: "123 Alphabet St, 12345, USA",
            },
          ],
          type: "icon",
          label: "",
          title: "",
          subtitle: "",
        },
        sectionName: "List",
      },
      {
        id: "4bbb3732-8537-492e-b53f-5a123130dab1",
        style: {
          designName: "design1",
          designSettings: {
            icon: "arrow",
            align: "start",
            border: false,
            spacing: {
              gap: {
                mobile: 10,
                desktop: 20,
              },
              top: {
                mobile: 25,
                desktop: 50,
              },
              bottom: {
                mobile: 25,
                desktop: 50,
              },
              padding: {
                mobile: 10,
                desktop: 20,
              },
            },
            background: true,
            leftTitlePosition: false,
            sectionBackground: {
              blur: false,
              color: "none",
              media: {
                imageId: "",
                imageUrl: "",
              },
              width: "fill",
              height: "fit",
              overlay: false,
              spacing: "l",
              parallax: false,
              greyScale: false,
              textColor: "light",
              blurEffect: "s",
              overlayEffect: "s",
            },
          },
        },
        content: {
          label: "",
          title: "FAQs",
          subtitle: "",
          accordions: [
            {
              id: "1de69273-4f21-4624-948a-916e6da3212b",
              text: "Add response here",
              title: "Question #1",
            },
            {
              id: "057b695e-fc2b-4446-9d74-8f7d629d3eef",
              text: "Add response here",
              title: "Question #2",
            },
            {
              id: "fbaa5bd3-cb52-4c9f-ad0d-2612f97ef65f",
              text: "Add response here",
              title: "Question #3",
            },
          ],
        },
        sectionName: "Accordion",
      },
    ],
  },
  {
    sections: [
      {
        id: "3ec6f59c-9759-4500-99a9-fff693cfe1ee",
        style: {
          designName: "design6",
          designSettings: {
            align: "center",
            video: true,
            border: false,
            height: {
              mobile: 350,
              desktop: 530,
            },
            mobile: "flex-col-reverse",
            spacing: {
              gap: {
                mobile: 20,
                desktop: 50,
              },
              top: {
                mobile: 25,
                desktop: 50,
              },
              bottom: {
                mobile: 25,
                desktop: 50,
              },
              padding: {
                mobile: 10,
                desktop: 20,
              },
            },
            showForm: true,
            showVideo: false,
            titleSize: "xl",
            background: true,
            showButtons: false,
            imageSetting: {
              objectFit: "cover",
              showImage: true,
              backgroundColor: "primary",
            },
            subtitleWidth: "50%",
            leftTitleWidth: "50%",
            leftTitlePosition: false,
            sectionBackground: {
              blur: false,
              color: "none",
              media: {
                imageId: "",
                imageUrl: "",
              },
              width: "fill",
              height: "fit",
              overlay: false,
              spacing: "xl",
              parallax: false,
              greyScale: false,
              textColor: "light",
              blurEffect: "s",
              overlayEffect: "s",
            },
          },
        },
        content: {
          form: {
            button: {
              id: "6e623d7e-3adf-4c70-ab74-b31fddab7944",
              link: "",
              text: "Submit",
            },
            fields: [
              {
                id: "a100ed0d-9c05-4257-ad1a-db85f5147b9e",
                type: "text",
                label: "First name",
                value: "First name",
                active: true,
                required: false,
                placeholder: "First name",
              },
              {
                id: "980f6c54-70ce-468b-8f3f-24b95c21fce7",
                type: "text",
                label: "Last name",
                value: "Last name",
                active: false,
                required: false,
                placeholder: "Last name",
              },
              {
                id: "2b000b31-d6a6-484e-acd3-a8ac88abfb6f",
                type: "email",
                label: "Email",
                value: "Email",
                active: true,
                required: true,
                placeholder: "Email",
              },
              {
                id: "533e7bd3-b527-4051-be2c-db291b6f7e0b",
                type: "tel",
                label: "Phone",
                value: "Phone",
                active: false,
                required: false,
                placeholder: "Phone",
              },
              {
                id: "149e69a8-7e24-4d63-9d74-7452af22e005",
                type: "textarea",
                label: "Message",
                value: "Message",
                active: false,
                required: false,
                placeholder: "Message",
              },
            ],
            countryCode: {
              code: "US",
              flag: "🇺🇸",
              name: "United States",
              dialCode: "+1",
            },
            successMessage: "Thank you! Your submission has been received",
          },
          label: "",
          title: "Contact",
          buttons: [
            {
              id: "3061d89e-a89c-4119-b4d4-721d1a53121a",
              link: "",
              text: "button 1",
              pageId: "",
              linkType: "internal",
              openNewTab: false,
              externalLink: "",
            },
            {
              id: "a9890b9d-7345-4516-93e4-2b8eebb3a6e0",
              link: "",
              text: "button 2",
              pageId: "",
              linkType: "internal",
              openNewTab: false,
              externalLink: "",
            },
          ],
          subtitle:
            "An inviting message that encourages visitors to get in touch.",
          mediaType: "image",
          actionType: "form",
          imageSetting: {
            altText: "",
            imageUrl: "",
          },
          videoSetting: {
            videoUrl: "",
          },
        },
        sectionName: "Banner",
      },
      {
        id: "cfa60d52-afca-4930-80c5-e329f6da0b44",
        style: {
          designName: "design1",
          designSettings: {
            grid: {
              mobile: 1,
              desktop: 3,
            },
            icon: true,
            align: "start",
            shape: "square",
            border: false,
            height: 50,
            layout: "row",
            layout2: "col",
            spacing: {
              gap: {
                mobile: 10,
                desktop: 20,
              },
              top: {
                mobile: 25,
                desktop: 50,
              },
              bottom: {
                mobile: 25,
                desktop: 50,
              },
              padding: {
                mobile: 10,
                desktop: 20,
              },
            },
            textSize: "m",
            iconColor: "primary",
            background: true,
            displayType: "grid",
            carouselSettings: {
              autoScroll: false,
              mobileWidth: 200,
              scrollSpeed: 2,
              desktopWidth: 200,
            },
            leftTitlePosition: false,
            sectionBackground: {
              blur: false,
              color: "none",
              media: {
                imageId: "",
                imageUrl: "",
              },
              width: "fill",
              height: "fit",
              overlay: false,
              spacing: "l",
              parallax: false,
              greyScale: false,
              textColor: "light",
              blurEffect: "s",
              overlayEffect: "s",
            },
          },
        },
        content: {
          list: [
            {
              id: "4ea1c4d0-eecc-482f-89ec-384b1874b3e1",
              icon: "Envelope",
              link: "",
              externalLink: "",
              image: "",
              imageId: "",
              linkType: "internal",
              openNewTab: false,
              pageId: "",
              text: "",
              title: "hello@team.co",
            },
            {
              id: "39945689-6b49-4daa-b5e7-acb1b851fca5",
              icon: "DeviceMobileCamera",
              link: "",
              externalLink: "",
              image: "",
              imageId: "",
              linkType: "internal",
              openNewTab: false,
              pageId: "",
              text: "",
              title: "+1 (234) 567 8900",
            },
            {
              id: "e618cec2-2d3a-4b28-9374-bf05cebc8ade",
              icon: "MapPin",
              link: "",
              externalLink: "",
              image: "",
              imageId: "",
              linkType: "internal",
              openNewTab: false,
              pageId: "",
              text: "",
              title: "123 Alphabet St, 12345, USA",
            },
          ],
          type: "icon",
          label: "",
          title: "",
          subtitle: "",
        },
        sectionName: "List",
      },
      {
        id: "4bbb3732-8537-492e-b53f-5a123130dab1",
        style: {
          designName: "design1",
          designSettings: {
            icon: "arrow",
            align: "start",
            border: false,
            spacing: {
              gap: {
                mobile: 10,
                desktop: 20,
              },
              top: {
                mobile: 25,
                desktop: 50,
              },
              bottom: {
                mobile: 25,
                desktop: 50,
              },
              padding: {
                mobile: 10,
                desktop: 20,
              },
            },
            background: true,
            leftTitlePosition: false,
            sectionBackground: {
              blur: false,
              color: "gray",
              media: {
                imageId: "",
                imageUrl: "",
              },
              width: "fill",
              height: "fit",
              overlay: false,
              spacing: "l",
              parallax: false,
              greyScale: false,
              textColor: "light",
              blurEffect: "s",
              overlayEffect: "s",
            },
          },
        },
        content: {
          label: "",
          title: "FAQs",
          subtitle: "",
          accordions: [
            {
              id: "1de69273-4f21-4624-948a-916e6da3212b",
              text: "Add response here",
              title: "Question #1",
            },
            {
              id: "057b695e-fc2b-4446-9d74-8f7d629d3eef",
              text: "Add response here",
              title: "Question #2",
            },
            {
              id: "fbaa5bd3-cb52-4c9f-ad0d-2612f97ef65f",
              text: "Add response here",
              title: "Question #3",
            },
          ],
        },
        sectionName: "Accordion",
      },
    ],
  },
];
