// actionTypes.ts

export const UPDATE_SELECTED_SECTION = "UPDATE_SELECTED_SECTION";
export const UPDATE_SELECTED_ITEM = "UPDATE_SELECTED_ITEM";
export const UPDATE_CONTENT = "UPDATE_CONTENT";
export const UPDATE_STYLE = "UPDATE_STYLE";
export const UPDATE_SELECTED_PALLET = "UPDATE_SELECTED_PALLET";
export const TOGGLE_PALLET = "TOGGLE_PALLET";
export const TOGGLE_SECTION_DESIGNS = "TOGGLE_SECTION_DESIGNS";
export const TOGGLE_CHOOSE_ICON = "TOGGLE_CHOOSE_ICON";
export const UPDATE_EDITOR_SECTIONS = "UPDATE_EDITOR_SECTIONS";
export const UPDATE_SECTION_INDEX = "UPDATE_SECTION_INDEX";
export const OPEN_SECTION_DESIGNS = "OPEN_SECTION_DESIGNS";
export const CLOSE_SECTION_DESIGNS = "CLOSE_SECTION_DESIGNS";
export const OPEN_CHOOSE_ICON = "OPEN_CHOOSE_ICON";
export const CLOSE_CHOOSE_ICON = "CLOSE_CHOOSE_ICON";
export const OPEN_PALLET = "OPEN_PALLET";
export const CLOSE_PALLET = "CLOSE_PALLET";
export const UPDATE_DESIGN_SETTINGS = "UPDATE_DESIGN_SETTINGS";
